Repository GazzolaLab/MiV-Simulator, pull requests merged in 2022-10, with the labels that each got.

#30 Use docker mounts to include user source code
  Dockerfile
  docs/tutorial/docker.md
Labels: documentation, enhancement, prio:high

#33 Addition of Gfluct3 stochastic conductance mechanism
  Makefile
  src/miv_simulator/mechanisms/Gfluct3.mod
  src/miv_simulator/mechanisms/__init__.py
  tests/mechanisms/test_gfluct3.py
  tests/mechanisms/test_mechanisms_compile_and_load.py
Labels: enhancement, prio:high

#34 Cluster setup scripts
  docs/tutorial/installation.md
  support/cluster/README.md
  support/cluster/expanse.sh
Labels: documentation, enhancement, prio:normal

#38 Fixes for network clamp functionality
  pyproject.toml
  src/miv_simulator/cells.py
  src/miv_simulator/clamps/network.py
  src/miv_simulator/env.py
  src/miv_simulator/plotting.py
  src/miv_simulator/spikedata.py
  src/scripts/analysis/cell_clamp.py
  src/scripts/analysis/network_clamp.py
  src/scripts/run_network.py
Labels: enhancement
